### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [sergpogo/FinalTask#6]
В комментарии к этому issue напишите ваши:

* Имя Фамилию (в дательном падеже)
* Адрес электронной почты, на которую выслать сертификат

**Comment by sergpogo** [comment]
Сергею Погодину
sergpogo@gmail.com

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by sergpogo** [comment]
Получено.
